# inspired by @holman's zsh config
export ZSH=$HOME/.dotfiles

export PROJECTS=~/code

for config_file ($ZSH/**/*.zsh) source $config_file

if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

autoload -U compinit
compinit

#for config_file ($ZSH/**/completion.sh) source $config_file
