# inspired by @holman's zsh config
PATH=$HOME/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/share/python:$HOME/bin:/usr/local/share/npm/bin:$PATH

export ZSH=$HOME/.dotfiles

export PROJECTS=~/code

for config_file ($ZSH/**/*.zsh) source $config_file

if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

autoload -U compinit
compinit

for config_file ($ZSH/**/completion.sh) source $config_file
